name: build release

# Controls when the action will run.
on:
  release:
    types: [created,published]
    branches: [github_action_test , main]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: "14"
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: "x64"
      - run: npm i
      - run: npm run package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: false
          files: |
            release/*.AppImage
            release/*.deb
            release/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
